// <auto-generated />
using Mercado.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mercado.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260901144444_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Mercado.Models.ItemNotaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProdId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Qntd")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NotaId");

                    b.HasIndex("ProdId");

                    b.ToTable("ItensNota");
                });

            modelBuilder.Entity("Mercado.Models.NotaModel", b =>
                {
                    b.Property<int>("N")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("N");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("Mercado.Models.ProdutoModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Saldo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Mercado.Models.ItemNotaModel", b =>
                {
                    b.HasOne("Mercado.Models.NotaModel", null)
                        .WithMany("Itens")
                        .HasForeignKey("NotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercado.Models.ProdutoModel", null)
                        .WithMany()
                        .HasForeignKey("ProdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mercado.Models.NotaModel", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
